{"nodes":[{"content":"The exception that is thrown for errors in an arithmetic, casting, or conversion operation.","nodes":[{"pos":[0,91],"content":"The exception that is thrown for errors in an arithmetic, casting, or conversion operation.","nodes":[{"content":"The exception that is thrown for errors in an arithmetic, casting, or conversion operation.","pos":[0,91]}]}],"pos":[669,761],"yaml":true},{"content":"<xref:System.ArithmeticException> is the base class for the following exceptions:  \n  \n-   <xref:System.DivideByZeroException>, which is thrown in integer division when the divisor is 0.  For example, attempting to divide 10 by 0 throws a <xref:System.DivideByZeroException> exception.  \n  \n-   <xref:System.NotFiniteNumberException>, which is thrown when an operation is performed on or returns <xref:System.Double.NaN?displayProperty=fullName>, <xref:System.Double.NegativeInfinity?displayProperty=fullName>, <xref:System.Double.PositiveInfinity?displayProperty=fullName>, <xref:System.Single.NaN?displayProperty=fullName>, <xref:System.Single.NegativeInfinity?displayProperty=fullName>, <xref:System.Single.PositiveInfinity?displayProperty=fullName>, and the programming language used does not support those values.  \n  \n-   <xref:System.OverflowException>, which is thrown when the result of an operation is outside the bounds of the target data type. That is, it is less than a number's `MinValue` property or greater than its `MaxValue` property.  For example, attempting to assign 200 + 200 to a <xref:System.Byte> value throws an <xref:System.OverflowException> exception, since 400 greater than 256, the upper bound of the <xref:System.Byte> data type.  \n  \n Your code should not handle or throw this exception. Instead, you should either handle or throw one of its derived classes, since it more precisely indicates the exact nature of the error.  \n  \n For a list of initial property values for an instance of <xref:System.ArithmeticException>, see the <xref:System.ArithmeticException> constructors.  \n  \n <xref:System.ArithmeticException> uses the HRESULT COR_E_ARITHMETIC, which has the value 0x80070216.","nodes":[{"pos":[0,81],"content":"<xref:System.ArithmeticException> is the base class for the following exceptions:","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.ArithmeticException&gt;</ph> is the base class for the following exceptions:","pos":[0,81],"source":"<xref:System.ArithmeticException> is the base class for the following exceptions:"}]},{"pos":[91,285],"content":"<xref:System.DivideByZeroException>, which is thrown in integer division when the divisor is 0.  For example, attempting to divide 10 by 0 throws a <xref:System.DivideByZeroException> exception.","nodes":[{"content":"<xref:System.DivideByZeroException>, which is thrown in integer division when the divisor is 0.  For example, attempting to divide 10 by 0 throws a <xref:System.DivideByZeroException> exception.","pos":[0,194],"nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.DivideByZeroException&gt;</ph>, which is thrown in integer division when the divisor is 0.","pos":[0,95],"source":"<xref:System.DivideByZeroException>, which is thrown in integer division when the divisor is 0."},{"content":"For example, attempting to divide 10 by 0 throws a <ph id=\"ph1\">&lt;xref:System.DivideByZeroException&gt;</ph> exception.","pos":[97,194],"source":"  For example, attempting to divide 10 by 0 throws a <xref:System.DivideByZeroException> exception."}]}]},{"pos":[295,818],"content":"<xref:System.NotFiniteNumberException>, which is thrown when an operation is performed on or returns <xref:System.Double.NaN?displayProperty=fullName>, <xref:System.Double.NegativeInfinity?displayProperty=fullName>, <xref:System.Double.PositiveInfinity?displayProperty=fullName>, <xref:System.Single.NaN?displayProperty=fullName>, <xref:System.Single.NegativeInfinity?displayProperty=fullName>, <xref:System.Single.PositiveInfinity?displayProperty=fullName>, and the programming language used does not support those values.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>, which is thrown when an operation is performed on or returns <ph id=\"ph2\">&lt;xref:System.Double.NaN?displayProperty=fullName&gt;</ph>, <ph id=\"ph3\">&lt;xref:System.Double.NegativeInfinity?displayProperty=fullName&gt;</ph>, <ph id=\"ph4\">&lt;xref:System.Double.PositiveInfinity?displayProperty=fullName&gt;</ph>, <ph id=\"ph5\">&lt;xref:System.Single.NaN?displayProperty=fullName&gt;</ph>, <ph id=\"ph6\">&lt;xref:System.Single.NegativeInfinity?displayProperty=fullName&gt;</ph>, <ph id=\"ph7\">&lt;xref:System.Single.PositiveInfinity?displayProperty=fullName&gt;</ph>, and the programming language used does not support those values.","pos":[0,523],"source":"<xref:System.NotFiniteNumberException>, which is thrown when an operation is performed on or returns <xref:System.Double.NaN?displayProperty=fullName>, <xref:System.Double.NegativeInfinity?displayProperty=fullName>, <xref:System.Double.PositiveInfinity?displayProperty=fullName>, <xref:System.Single.NaN?displayProperty=fullName>, <xref:System.Single.NegativeInfinity?displayProperty=fullName>, <xref:System.Single.PositiveInfinity?displayProperty=fullName>, and the programming language used does not support those values."}]},{"pos":[828,1261],"content":"<xref:System.OverflowException>, which is thrown when the result of an operation is outside the bounds of the target data type. That is, it is less than a number's `MinValue` property or greater than its `MaxValue` property.  For example, attempting to assign 200 + 200 to a <xref:System.Byte> value throws an <xref:System.OverflowException> exception, since 400 greater than 256, the upper bound of the <xref:System.Byte> data type.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.OverflowException&gt;</ph>, which is thrown when the result of an operation is outside the bounds of the target data type.","pos":[0,127],"source":"<xref:System.OverflowException>, which is thrown when the result of an operation is outside the bounds of the target data type."},{"content":"That is, it is less than a number's <ph id=\"ph1\">`MinValue`</ph> property or greater than its <ph id=\"ph2\">`MaxValue`</ph> property.","pos":[128,224],"source":" That is, it is less than a number's `MinValue` property or greater than its `MaxValue` property."},{"content":"For example, attempting to assign 200 + 200 to a <ph id=\"ph1\">&lt;xref:System.Byte&gt;</ph> value throws an <ph id=\"ph2\">&lt;xref:System.OverflowException&gt;</ph> exception, since 400 greater than 256, the upper bound of the <ph id=\"ph3\">&lt;xref:System.Byte&gt;</ph> data type.","pos":[226,433],"source":"  For example, attempting to assign 200 + 200 to a <xref:System.Byte> value throws an <xref:System.OverflowException> exception, since 400 greater than 256, the upper bound of the <xref:System.Byte> data type."}]},{"pos":[1268,1456],"content":"Your code should not handle or throw this exception. Instead, you should either handle or throw one of its derived classes, since it more precisely indicates the exact nature of the error.","nodes":[{"content":"Your code should not handle or throw this exception. Instead, you should either handle or throw one of its derived classes, since it more precisely indicates the exact nature of the error.","pos":[0,188],"nodes":[{"content":"Your code should not handle or throw this exception.","pos":[0,52]},{"content":"Instead, you should either handle or throw one of its derived classes, since it more precisely indicates the exact nature of the error.","pos":[53,188]}]}]},{"pos":[1463,1610],"content":"For a list of initial property values for an instance of <xref:System.ArithmeticException>, see the <xref:System.ArithmeticException> constructors.","nodes":[{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArithmeticException&gt;</ph>, see the <ph id=\"ph2\">&lt;xref:System.ArithmeticException&gt;</ph> constructors.","pos":[0,147],"source":"For a list of initial property values for an instance of <xref:System.ArithmeticException>, see the <xref:System.ArithmeticException> constructors."}]},{"pos":[1617,1717],"content":"<xref:System.ArithmeticException> uses the HRESULT COR_E_ARITHMETIC, which has the value 0x80070216.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.ArithmeticException&gt;</ph> uses the HRESULT COR_E_ARITHMETIC, which has the value 0x80070216.","pos":[0,100],"source":"<xref:System.ArithmeticException> uses the HRESULT COR_E_ARITHMETIC, which has the value 0x80070216."}]}],"pos":[772,2504],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class.","nodes":[{"pos":[0,88],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArithmeticException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class."}],"pos":[5138,5227],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The arithmetic operation is not allowed.\" This message takes into account the current system culture.  \n  \n The following table shows initial property values for an instance of <xref:System.ArithmeticException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,262],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The arithmetic operation is not allowed.\" This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The arithmetic operation is not allowed.\" This message takes into account the current system culture.","pos":[0,262],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"The arithmetic operation is not allowed.\"","pos":[0,202],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The arithmetic operation is not allowed.\""},{"content":"This message takes into account the current system culture.","pos":[203,262]}]}]},{"pos":[269,372],"content":"The following table shows initial property values for an instance of <xref:System.ArithmeticException>.","nodes":[{"content":"The following table shows initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArithmeticException&gt;</ph>.","pos":[0,103],"source":"The following table shows initial property values for an instance of <xref:System.ArithmeticException>."}]},{"pos":[379,387],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[388,393],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[429,470],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[471,478],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[483,517],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[518,553],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[5238,5804],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with a specified error message.","nodes":[{"pos":[0,119],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArithmeticException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with a specified error message."}],"pos":[7484,7604],"yaml":true},{"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n The following table shows initial property values for an instance of <xref:System.ArithmeticException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,199],"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[0,78],"source":"The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[79,199]}]},{"pos":[206,309],"content":"The following table shows initial property values for an instance of <xref:System.ArithmeticException>.","nodes":[{"content":"The following table shows initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArithmeticException&gt;</ph>.","pos":[0,103],"source":"The following table shows initial property values for an instance of <xref:System.ArithmeticException>."}]},{"pos":[316,324],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[325,330],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[366,407],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[408,455],"content":"The null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"The null reference (`Nothing` in Visual Basic)."},{"pos":[460,494],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[495,520],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[7615,8146],"yaml":true,"extradata":"MT"},{"content":"A <xref href=\"System.String\"></xref> that describes the error.","nodes":[{"pos":[0,62],"content":"A <ph id=\"ph1\">&lt;xref href=\"System.String\"&gt;&lt;/xref&gt;</ph> that describes the error.","source":"A <xref href=\"System.String\"></xref> that describes the error."}],"pos":[8293,8356],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with serialized data.","nodes":[{"pos":[0,109],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArithmeticException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with serialized data."}],"pos":[10287,10397],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"pos":[0,231],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/docs/framework/serialization/xml-and-soap-serialization.md)</ept>.","pos":[114,231],"source":" For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)."}]}],"pos":[10408,10640],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[10912,10962],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[11057,11117],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,194],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArithmeticException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[12464,12659],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows initial property values for an instance of <xref:System.ArithmeticException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,465],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic) if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,465],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[472,575],"content":"The following table shows initial property values for an instance of <xref:System.ArithmeticException>.","nodes":[{"content":"The following table shows initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArithmeticException&gt;</ph>.","pos":[0,103],"source":"The following table shows initial property values for an instance of <xref:System.ArithmeticException>."}]},{"pos":[582,590],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[591,596],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[632,673],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[674,704],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[709,743],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[744,769],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[12670,13450],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[13623,13685],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,212],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not a null reference, the current exception is raised in a <ph id=\"ph2\">`catch`</ph> block that handles the inner exception.","pos":[58,212],"source":" If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[13758,13971],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.ArithmeticException\n  commentId: T:System.ArithmeticException\n  id: ArithmeticException\n  children:\n  - System.ArithmeticException.#ctor\n  - System.ArithmeticException.#ctor(System.String)\n  - System.ArithmeticException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.ArithmeticException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ArithmeticException\n  nameWithType: ArithmeticException\n  fullName: System.ArithmeticException\n  type: Class\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: The exception that is thrown for errors in an arithmetic, casting, or conversion operation.\n  remarks: \"<xref:System.ArithmeticException> is the base class for the following exceptions:  \\n  \\n-   <xref:System.DivideByZeroException>, which is thrown in integer division when the divisor is 0.  For example, attempting to divide 10 by 0 throws a <xref:System.DivideByZeroException> exception.  \\n  \\n-   <xref:System.NotFiniteNumberException>, which is thrown when an operation is performed on or returns <xref:System.Double.NaN?displayProperty=fullName>, <xref:System.Double.NegativeInfinity?displayProperty=fullName>, <xref:System.Double.PositiveInfinity?displayProperty=fullName>, <xref:System.Single.NaN?displayProperty=fullName>, <xref:System.Single.NegativeInfinity?displayProperty=fullName>, <xref:System.Single.PositiveInfinity?displayProperty=fullName>, and the programming language used does not support those values.  \\n  \\n-   <xref:System.OverflowException>, which is thrown when the result of an operation is outside the bounds of the target data type. That is, it is less than a number's `MinValue` property or greater than its `MaxValue` property.  For example, attempting to assign 200 + 200 to a <xref:System.Byte> value throws an <xref:System.OverflowException> exception, since 400 greater than 256, the upper bound of the <xref:System.Byte> data type.  \\n  \\n Your code should not handle or throw this exception. Instead, you should either handle or throw one of its derived classes, since it more precisely indicates the exact nature of the error.  \\n  \\n For a list of initial property values for an instance of <xref:System.ArithmeticException>, see the <xref:System.ArithmeticException> constructors.  \\n  \\n <xref:System.ArithmeticException> uses the HRESULT COR_E_ARITHMETIC, which has the value 0x80070216.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class ArithmeticException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  derivedClasses:\n  - System.DivideByZeroException\n  - System.NotFiniteNumberException\n  - System.OverflowException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArithmeticException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArithmeticException.#ctor\n  commentId: M:System.ArithmeticException.#ctor\n  id: '#ctor'\n  parent: System.ArithmeticException\n  langs:\n  - csharp\n  name: ArithmeticException()\n  nameWithType: ArithmeticException.ArithmeticException()\n  fullName: ArithmeticException.ArithmeticException()\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"The arithmetic operation is not allowed.\\\" This message takes into account the current system culture.  \\n  \\n The following table shows initial property values for an instance of <xref:System.ArithmeticException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public ArithmeticException ();\n    parameters: []\n  overload: System.ArithmeticException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArithmeticException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArithmeticException.#ctor(System.String)\n  commentId: M:System.ArithmeticException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.ArithmeticException\n  langs:\n  - csharp\n  name: ArithmeticException(String)\n  nameWithType: ArithmeticException.ArithmeticException(String)\n  fullName: ArithmeticException.ArithmeticException(String)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with a specified error message.\n  remarks: \"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows initial property values for an instance of <xref:System.ArithmeticException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ArithmeticException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref href=\"System.String\"></xref> that describes the error.\n  overload: System.ArithmeticException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArithmeticException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArithmeticException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.ArithmeticException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.ArithmeticException\n  langs:\n  - csharp\n  name: ArithmeticException(SerializationInfo, StreamingContext)\n  nameWithType: ArithmeticException.ArithmeticException(SerializationInfo, StreamingContext)\n  fullName: ArithmeticException.ArithmeticException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).\n  syntax:\n    content: protected ArithmeticException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.ArithmeticException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArithmeticException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArithmeticException.#ctor(System.String,System.Exception)\n  commentId: M:System.ArithmeticException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.ArithmeticException\n  langs:\n  - csharp\n  name: ArithmeticException(String, Exception)\n  nameWithType: ArithmeticException.ArithmeticException(String, Exception)\n  fullName: ArithmeticException.ArithmeticException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArithmeticException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows initial property values for an instance of <xref:System.ArithmeticException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ArithmeticException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.ArithmeticException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArithmeticException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.ArithmeticException.#ctor\n  parent: System.ArithmeticException\n  isExternal: false\n  name: ArithmeticException()\n  nameWithType: ArithmeticException.ArithmeticException()\n  fullName: ArithmeticException.ArithmeticException()\n- uid: System.ArithmeticException.#ctor(System.String)\n  parent: System.ArithmeticException\n  isExternal: false\n  name: ArithmeticException(String)\n  nameWithType: ArithmeticException.ArithmeticException(String)\n  fullName: ArithmeticException.ArithmeticException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.ArithmeticException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.ArithmeticException\n  isExternal: false\n  name: ArithmeticException(SerializationInfo, StreamingContext)\n  nameWithType: ArithmeticException.ArithmeticException(SerializationInfo, StreamingContext)\n  fullName: ArithmeticException.ArithmeticException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.ArithmeticException.#ctor(System.String,System.Exception)\n  parent: System.ArithmeticException\n  isExternal: false\n  name: ArithmeticException(String, Exception)\n  nameWithType: ArithmeticException.ArithmeticException(String, Exception)\n  fullName: ArithmeticException.ArithmeticException(String, Exception)\n- uid: System.ArithmeticException.#ctor*\n  parent: System.ArithmeticException\n  isExternal: false\n  name: ArithmeticException\n  nameWithType: ArithmeticException.ArithmeticException\n  fullName: ArithmeticException.ArithmeticException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArithmeticException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}