{"nodes":[{"content":"The exception that is thrown when a floating-point value is positive infinity, negative infinity, or Not-a-Number (NaN).","nodes":[{"pos":[0,120],"content":"The exception that is thrown when a floating-point value is positive infinity, negative infinity, or Not-a-Number (NaN).","nodes":[{"content":"The exception that is thrown when a floating-point value is positive infinity, negative infinity, or Not-a-Number (NaN).","pos":[0,120]}]}],"pos":[1131,1252],"yaml":true},{"content":"<xref:System.NotFiniteNumberException> is available for programming languages that do not support the concepts of infinity and Not-a-Number in floating-point operations.  \n  \n <xref:System.NotFiniteNumberException> uses the HRESULT COR_E_NOTFINITENUMBER, which has the value 0x80131528.  \n  \n For a list of initial property values for an instance of <xref:System.NotFiniteNumberException>, see the <xref:System.NotFiniteNumberException.%23ctor%2A> constructors.","nodes":[{"pos":[0,169],"content":"<xref:System.NotFiniteNumberException> is available for programming languages that do not support the concepts of infinity and Not-a-Number in floating-point operations.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph> is available for programming languages that do not support the concepts of infinity and Not-a-Number in floating-point operations.","pos":[0,169],"source":"<xref:System.NotFiniteNumberException> is available for programming languages that do not support the concepts of infinity and Not-a-Number in floating-point operations."}]},{"pos":[176,286],"content":"<xref:System.NotFiniteNumberException> uses the HRESULT COR_E_NOTFINITENUMBER, which has the value 0x80131528.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph> uses the HRESULT COR_E_NOTFINITENUMBER, which has the value 0x80131528.","pos":[0,110],"source":"<xref:System.NotFiniteNumberException> uses the HRESULT COR_E_NOTFINITENUMBER, which has the value 0x80131528."}]},{"pos":[293,461],"content":"For a list of initial property values for an instance of <xref:System.NotFiniteNumberException>, see the <xref:System.NotFiniteNumberException.%23ctor%2A> constructors.","nodes":[{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>, see the <ph id=\"ph2\">&lt;xref:System.NotFiniteNumberException.%23ctor%2A&gt;</ph> constructors.","pos":[0,168],"source":"For a list of initial property values for an instance of <xref:System.NotFiniteNumberException>, see the <xref:System.NotFiniteNumberException.%23ctor%2A> constructors."}]}],"pos":[1263,1731],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class.","nodes":[{"pos":[0,93],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NotFiniteNumberException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class."}],"pos":[3861,3955],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The number encountered was not a finite quantity.\" This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,271],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The number encountered was not a finite quantity.\" This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The number encountered was not a finite quantity.\" This message takes into account the current system culture.","pos":[0,271],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"The number encountered was not a finite quantity.\"","pos":[0,211],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"The number encountered was not a finite quantity.\""},{"content":"This message takes into account the current system culture.","pos":[212,271]}]}]},{"pos":[278,390],"content":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>."}]},{"pos":[397,405],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[406,411],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[447,488],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[489,534],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[539,573],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[574,609],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[3966,4588],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with the invalid number.","nodes":[{"pos":[0,117],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NotFiniteNumberException\"&gt;&lt;/xref&gt;</ph> class with the invalid number.","source":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with the invalid number."}],"pos":[5979,6097],"yaml":true},{"content":"The `offendingNumber` parameter must be both a <xref:System.Double> and an invalid number.  \n  \n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.NotFiniteNumberException.OffendingNumber%2A>|The invalid number.|","nodes":[{"pos":[0,90],"content":"The <ph id=\"ph1\">`offendingNumber`</ph> parameter must be both a <ph id=\"ph2\">&lt;xref:System.Double&gt;</ph> and an invalid number.","source":"The `offendingNumber` parameter must be both a <xref:System.Double> and an invalid number."},{"pos":[97,209],"content":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>."}]},{"pos":[216,224],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[225,230],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[266,307],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[308,353],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[358,415],"content":"<xref:System.NotFiniteNumberException.OffendingNumber%2A>","nodes":[]},{"pos":[416,435],"content":"The invalid number.","nodes":[{"content":"The invalid number.","pos":[0,19]}]}],"pos":[6108,6554],"yaml":true,"extradata":"MT"},{"content":"The value of the argument that caused the exception.","nodes":[{"pos":[0,52],"content":"The value of the argument that caused the exception.","nodes":[{"content":"The value of the argument that caused the exception.","pos":[0,52]}]}],"pos":[6722,6775],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message.","nodes":[{"pos":[0,124],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NotFiniteNumberException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message."}],"pos":[8088,8213],"yaml":true},{"content":"Ensure that the `message` string is understandable to the user and that it is localized for the current culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,112],"content":"Ensure that the <ph id=\"ph1\">`message`</ph> string is understandable to the user and that it is localized for the current culture.","source":"Ensure that the `message` string is understandable to the user and that it is localized for the current culture."},{"pos":[119,231],"content":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>."}]},{"pos":[238,246],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[247,252],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[288,329],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[330,375],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[380,414],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[415,440],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[8224,8675],"yaml":true,"extradata":"MT"},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[8827,8865],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with serialized data.","nodes":[{"pos":[0,114],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NotFiniteNumberException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with serialized data."}],"pos":[10502,10617],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","nodes":[{"pos":[0,113],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]}]}],"pos":[10628,10742],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[11019,11069],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[11164,11224],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message and the invalid number.","nodes":[{"pos":[0,147],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NotFiniteNumberException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and the invalid number.","source":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message and the invalid number."}],"pos":[12603,12751],"yaml":true},{"content":"Ensure that the `message` string is understandable to the user and that it is localized for the current culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The error message string.|  \n|<xref:System.NotFiniteNumberException.OffendingNumber%2A>|The invalid number.|","nodes":[{"pos":[0,112],"content":"Ensure that the <ph id=\"ph1\">`message`</ph> string is understandable to the user and that it is localized for the current culture.","source":"Ensure that the `message` string is understandable to the user and that it is localized for the current culture."},{"pos":[119,231],"content":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>."}]},{"pos":[238,246],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[247,252],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[288,329],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[330,375],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[380,414],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[415,440],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]},{"pos":[445,502],"content":"<xref:System.NotFiniteNumberException.OffendingNumber%2A>","nodes":[]},{"pos":[503,522],"content":"The invalid number.","nodes":[{"content":"The invalid number.","pos":[0,19]}]}],"pos":[12762,13296],"yaml":true,"extradata":"MT"},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[13472,13510],"yaml":true},{"content":"The value of the argument that caused the exception.","nodes":[{"pos":[0,52],"content":"The value of the argument that caused the exception.","nodes":[{"content":"The value of the argument that caused the exception.","pos":[0,52]}]}],"pos":[13581,13634],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message and a reference to the inner exception that is root cause of this exception.","nodes":[{"pos":[0,200],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NotFiniteNumberException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is root cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message and a reference to the inner exception that is root cause of this exception."}],"pos":[15031,15232],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,424],"content":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,179],"source":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[180,424],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[431,543],"content":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>."}]},{"pos":[550,558],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[559,564],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[600,641],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[642,672],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[677,711],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[712,737],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[15243,15991],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[16169,16231],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,240],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic), the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,240],"source":" If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[16304,16545],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message, the invalid number, and a reference to the inner exception that is root cause of this exception.","nodes":[{"pos":[0,221],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.NotFiniteNumberException\"&gt;&lt;/xref&gt;</ph> class with a specified error message, the invalid number, and a reference to the inner exception that is root cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message, the invalid number, and a reference to the inner exception that is root cause of this exception."}],"pos":[18008,18230],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|  \n|<xref:System.NotFiniteNumberException.OffendingNumber%2A>|The invalid number.|","nodes":[{"pos":[0,424],"content":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,179],"source":"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[180,424],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[431,543],"content":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>."}]},{"pos":[550,558],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[559,564],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[600,641],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[642,672],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[677,711],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[712,737],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]},{"pos":[742,799],"content":"<xref:System.NotFiniteNumberException.OffendingNumber%2A>","nodes":[]},{"pos":[800,819],"content":"The invalid number.","nodes":[{"content":"The invalid number.","pos":[0,19]}]}],"pos":[18241,19072],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[19274,19336],"yaml":true},{"content":"The value of the argument that caused the exception.","nodes":[{"pos":[0,52],"content":"The value of the argument that caused the exception.","nodes":[{"content":"The value of the argument that caused the exception.","pos":[0,52]}]}],"pos":[19407,19460],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,240],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic), the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,240],"source":" If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[19533,19774],"yaml":true},{"content":"Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the invalid number and additional exception information.","nodes":[{"pos":[0,145],"content":"Sets the <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;&lt;/xref&gt;</ph> object with the invalid number and additional exception information.","source":"Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the invalid number and additional exception information."}],"pos":[21395,21541],"yaml":true},{"content":"<xref:System.TypeLoadException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization, the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.  \n  \n For more information, see <xref:System.Runtime.Serialization.SerializationInfo>.","nodes":[{"pos":[0,326],"content":"<xref:System.TypeLoadException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization, the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.","nodes":[{"content":"<xref:System.TypeLoadException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization, the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.","pos":[0,326],"nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.TypeLoadException.GetObjectData%2A&gt;</ph> sets a <ph id=\"ph2\">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> with all the exception object data targeted for serialization.","pos":[0,172],"source":"<xref:System.TypeLoadException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization."},{"content":"During deserialization, the exception object is reconstituted from the <ph id=\"ph1\">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph> transmitted over the stream.","pos":[173,326],"source":" During deserialization, the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream."}]}]},{"pos":[333,413],"content":"For more information, see <xref:System.Runtime.Serialization.SerializationInfo>.","nodes":[{"content":"For more information, see <ph id=\"ph1\">&lt;xref:System.Runtime.Serialization.SerializationInfo&gt;</ph>.","pos":[0,80],"source":"For more information, see <xref:System.Runtime.Serialization.SerializationInfo>."}]}],"pos":[21552,21970],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[22298,22348],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[22443,22503],"yaml":true},{"content":"The <code>info</code> object is `null`.","nodes":[{"pos":[0,39],"content":"The <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">info</ph><ept id=\"p1\">&lt;/code&gt;</ept> object is <ph id=\"ph2\">`null`</ph>.","source":"The <code>info</code> object is `null`."}],"pos":[22678,22718],"yaml":true},{"content":"Gets the invalid number that is a positive infinity, a negative infinity, or Not-a-Number (NaN).","nodes":[{"pos":[0,96],"content":"Gets the invalid number that is a positive infinity, a negative infinity, or Not-a-Number (NaN).","nodes":[{"content":"Gets the invalid number that is a positive infinity, a negative infinity, or Not-a-Number (NaN).","pos":[0,96]}]}],"pos":[23958,24055],"yaml":true},{"content":"The <xref:System.NotFiniteNumberException.OffendingNumber%2A> property returns the same value as was passed into the constructor, or zero if no value was supplied. Override the <xref:System.NotFiniteNumberException.OffendingNumber%2A> property to customize the content or format of the invalid value.  \n  \n This property is read-only.","nodes":[{"pos":[0,300],"content":"The <xref:System.NotFiniteNumberException.OffendingNumber%2A> property returns the same value as was passed into the constructor, or zero if no value was supplied. Override the <xref:System.NotFiniteNumberException.OffendingNumber%2A> property to customize the content or format of the invalid value.","nodes":[{"content":"The <xref:System.NotFiniteNumberException.OffendingNumber%2A> property returns the same value as was passed into the constructor, or zero if no value was supplied. Override the <xref:System.NotFiniteNumberException.OffendingNumber%2A> property to customize the content or format of the invalid value.","pos":[0,300],"nodes":[{"content":"The <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;</ph> property returns the same value as was passed into the constructor, or zero if no value was supplied.","pos":[0,163],"source":"The <xref:System.NotFiniteNumberException.OffendingNumber%2A> property returns the same value as was passed into the constructor, or zero if no value was supplied."},{"content":"Override the <ph id=\"ph1\">&lt;xref:System.NotFiniteNumberException.OffendingNumber%2A&gt;</ph> property to customize the content or format of the invalid value.","pos":[164,300],"source":" Override the <xref:System.NotFiniteNumberException.OffendingNumber%2A> property to customize the content or format of the invalid value."}]}]},{"pos":[307,334],"content":"This property is read-only.","nodes":[{"content":"This property is read-only.","pos":[0,27]}]}],"pos":[24066,24405],"yaml":true,"extradata":"MT"},{"content":"The invalid number.","nodes":[{"pos":[0,19],"content":"The invalid number.","nodes":[{"content":"The invalid number.","pos":[0,19]}]}],"pos":[24524,24544],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.NotFiniteNumberException\n  commentId: T:System.NotFiniteNumberException\n  id: NotFiniteNumberException\n  children:\n  - System.NotFiniteNumberException.#ctor\n  - System.NotFiniteNumberException.#ctor(System.Double)\n  - System.NotFiniteNumberException.#ctor(System.String)\n  - System.NotFiniteNumberException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.NotFiniteNumberException.#ctor(System.String,System.Double)\n  - System.NotFiniteNumberException.#ctor(System.String,System.Exception)\n  - System.NotFiniteNumberException.#ctor(System.String,System.Double,System.Exception)\n  - System.NotFiniteNumberException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.NotFiniteNumberException.OffendingNumber\n  langs:\n  - csharp\n  name: NotFiniteNumberException\n  nameWithType: NotFiniteNumberException\n  fullName: System.NotFiniteNumberException\n  type: Class\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: The exception that is thrown when a floating-point value is positive infinity, negative infinity, or Not-a-Number (NaN).\n  remarks: \"<xref:System.NotFiniteNumberException> is available for programming languages that do not support the concepts of infinity and Not-a-Number in floating-point operations.  \\n  \\n <xref:System.NotFiniteNumberException> uses the HRESULT COR_E_NOTFINITENUMBER, which has the value 0x80131528.  \\n  \\n For a list of initial property values for an instance of <xref:System.NotFiniteNumberException>, see the <xref:System.NotFiniteNumberException.%23ctor%2A> constructors.\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class NotFiniteNumberException : ArithmeticException\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.ArithmeticException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.#ctor\n  commentId: M:System.NotFiniteNumberException.#ctor\n  id: '#ctor'\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: NotFiniteNumberException()\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException()\n  fullName: NotFiniteNumberException.NotFiniteNumberException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"The number encountered was not a finite quantity.\\\" This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public NotFiniteNumberException ();\n    parameters: []\n  overload: System.NotFiniteNumberException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.#ctor(System.Double)\n  commentId: M:System.NotFiniteNumberException.#ctor(System.Double)\n  id: '#ctor(System.Double)'\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: NotFiniteNumberException(Double)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(Double)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(Double)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with the invalid number.\n  remarks: \"The `offendingNumber` parameter must be both a <xref:System.Double> and an invalid number.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.NotFiniteNumberException.OffendingNumber%2A>|The invalid number.|\"\n  syntax:\n    content: public NotFiniteNumberException (double offendingNumber);\n    parameters:\n    - id: offendingNumber\n      type: System.Double\n      description: The value of the argument that caused the exception.\n  overload: System.NotFiniteNumberException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.#ctor(System.String)\n  commentId: M:System.NotFiniteNumberException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: NotFiniteNumberException(String)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message.\n  remarks: \"Ensure that the `message` string is understandable to the user and that it is localized for the current culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public NotFiniteNumberException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.NotFiniteNumberException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.NotFiniteNumberException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: NotFiniteNumberException(SerializationInfo, StreamingContext)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(SerializationInfo, StreamingContext)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.\n  syntax:\n    content: protected NotFiniteNumberException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.NotFiniteNumberException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double)\n  commentId: M:System.NotFiniteNumberException.#ctor(System.String,System.Double)\n  id: '#ctor(System.String,System.Double)'\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: NotFiniteNumberException(String, Double)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String, Double)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String, Double)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message and the invalid number.\n  remarks: \"Ensure that the `message` string is understandable to the user and that it is localized for the current culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.NotFiniteNumberException.OffendingNumber%2A>|The invalid number.|\"\n  syntax:\n    content: public NotFiniteNumberException (string message, double offendingNumber);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: offendingNumber\n      type: System.Double\n      description: The value of the argument that caused the exception.\n  overload: System.NotFiniteNumberException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.#ctor(System.String,System.Exception)\n  commentId: M:System.NotFiniteNumberException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: NotFiniteNumberException(String, Exception)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String, Exception)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String, Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message and a reference to the inner exception that is root cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public NotFiniteNumberException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.NotFiniteNumberException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double,System.Exception)\n  commentId: M:System.NotFiniteNumberException.#ctor(System.String,System.Double,System.Exception)\n  id: '#ctor(System.String,System.Double,System.Exception)'\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: NotFiniteNumberException(String, Double, Exception)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String, Double, Exception)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String, Double, Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.NotFiniteNumberException\"></xref> class with a specified error message, the invalid number, and a reference to the inner exception that is root cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception can include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.NotFiniteNumberException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|  \\n|<xref:System.NotFiniteNumberException.OffendingNumber%2A>|The invalid number.|\"\n  syntax:\n    content: public NotFiniteNumberException (string message, double offendingNumber, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: offendingNumber\n      type: System.Double\n      description: The value of the argument that caused the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.NotFiniteNumberException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.NotFiniteNumberException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: NotFiniteNumberException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: NotFiniteNumberException.GetObjectData(SerializationInfo, StreamingContext)\n  type: Method\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Sets the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object with the invalid number and additional exception information.\n  remarks: \"<xref:System.TypeLoadException.GetObjectData%2A> sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization. During deserialization, the exception object is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> transmitted over the stream.  \\n  \\n For more information, see <xref:System.Runtime.Serialization.SerializationInfo>.\"\n  syntax:\n    content: >-\n      [System.Security.SecurityCritical]\n\n      public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.NotFiniteNumberException.GetObjectData*\n  exceptions:\n  - type: System.ArgumentNullException\n    commentId: T:System.ArgumentNullException\n    description: The <code>info</code> object is `null`.\n  attributes:\n  - type: System.Security.SecurityCriticalAttribute\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.NotFiniteNumberException.OffendingNumber\n  commentId: P:System.NotFiniteNumberException.OffendingNumber\n  id: OffendingNumber\n  parent: System.NotFiniteNumberException\n  langs:\n  - csharp\n  name: OffendingNumber\n  nameWithType: NotFiniteNumberException.OffendingNumber\n  fullName: NotFiniteNumberException.OffendingNumber\n  type: Property\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Gets the invalid number that is a positive infinity, a negative infinity, or Not-a-Number (NaN).\n  remarks: \"The <xref:System.NotFiniteNumberException.OffendingNumber%2A> property returns the same value as was passed into the constructor, or zero if no value was supplied. Override the <xref:System.NotFiniteNumberException.OffendingNumber%2A> property to customize the content or format of the invalid value.  \\n  \\n This property is read-only.\"\n  syntax:\n    content: public double OffendingNumber { get; }\n    return:\n      type: System.Double\n      description: The invalid number.\n  overload: System.NotFiniteNumberException.OffendingNumber*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.ArithmeticException\n  parent: System\n  isExternal: false\n  name: ArithmeticException\n  nameWithType: ArithmeticException\n  fullName: System.ArithmeticException\n- uid: System.ArgumentNullException\n  parent: System\n  isExternal: false\n  name: ArgumentNullException\n  nameWithType: ArgumentNullException\n  fullName: System.ArgumentNullException\n- uid: System.NotFiniteNumberException.#ctor\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException()\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException()\n  fullName: NotFiniteNumberException.NotFiniteNumberException()\n- uid: System.NotFiniteNumberException.#ctor(System.Double)\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException(Double)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(Double)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(Double)\n- uid: System.Double\n  parent: System\n  isExternal: false\n  name: Double\n  nameWithType: Double\n  fullName: System.Double\n- uid: System.NotFiniteNumberException.#ctor(System.String)\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException(String)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.NotFiniteNumberException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException(SerializationInfo, StreamingContext)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(SerializationInfo, StreamingContext)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double)\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException(String, Double)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String, Double)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String, Double)\n- uid: System.NotFiniteNumberException.#ctor(System.String,System.Exception)\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException(String, Exception)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String, Exception)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.NotFiniteNumberException.#ctor(System.String,System.Double,System.Exception)\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException(String, Double, Exception)\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException(String, Double, Exception)\n  fullName: NotFiniteNumberException.NotFiniteNumberException(String, Double, Exception)\n- uid: System.NotFiniteNumberException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: NotFiniteNumberException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: NotFiniteNumberException.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.NotFiniteNumberException.OffendingNumber\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: OffendingNumber\n  nameWithType: NotFiniteNumberException.OffendingNumber\n  fullName: NotFiniteNumberException.OffendingNumber\n- uid: System.NotFiniteNumberException.#ctor*\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: NotFiniteNumberException\n  nameWithType: NotFiniteNumberException.NotFiniteNumberException\n  fullName: NotFiniteNumberException.NotFiniteNumberException\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n- uid: System.NotFiniteNumberException.GetObjectData*\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: GetObjectData\n  nameWithType: NotFiniteNumberException.GetObjectData\n  fullName: NotFiniteNumberException.GetObjectData\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n- uid: System.NotFiniteNumberException.OffendingNumber*\n  parent: System.NotFiniteNumberException\n  isExternal: false\n  name: OffendingNumber\n  nameWithType: NotFiniteNumberException.OffendingNumber\n  fullName: NotFiniteNumberException.OffendingNumber\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/NotFiniteNumberException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}